name: Bump and Tag
on: [workflow_dispatch]

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    name: Bump version and create tag
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.SDK_SYNC_PAT }}
          dry_run: true
          commit_sha: true
          default_bump: patch
