name: My Go Builder

on:
  workflow_dispatch:
#  push:

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version  }}
    name: Bump version and create tag
    steps:
      - name: Bump version and push tag
        id: tag_version
        env: 
          PRE: true
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.SDK_SYNC_PAT }}
          dry_run: true
      - name: Show Bump and Tag Vars
        run: |
          echo "new_version : ${{ steps.tag_version.outputs.new_version  }}"
          echo "new_tag : ${{ steps.tag_version.outputs.new_tag  }}"
          echo "GITHUB_REF_NAME: ${{env.GITHUB_REF_NAME}}"
          env
  show-vars:
    runs-on: ubuntu-latest
    needs: bump-and-tag
    steps:
      - name: Show Vars from other job
        run: |
          echo "new_version : ${{ needs.bump-and-tag.outputs.new_version  }}"
          echo "package version" | tee version.go
          echo "" | tee -a version.go
          echo "const VERSION = \"v${{ needs.bump-and-tag.outputs.new_version  }}\"" | tee -a version.go
          cat version.go
#
# Next steps. Do a checkout of the project first
# update the version.go in the release branch
# Then run the bump-and-tag action on the release branch
