name: My Go Builder

on:
  workflow_dispatch:
  push:

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    name: Bump version and create tag
    steps:
      - name: Bump version and push tag
        id: tag_version
        env: 
          PRE: true
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.SDK_SYNC_PAT }}
          dry_run: true
      - name: Show Bump and Tag Vars
        run: |
          echo "new_version : ${{ steps.tag_version.outputs.new_version  }}"
          echo "new_tag : ${{ steps.tag_version.outputs.new_tag  }}"
          echo "GITHUB_REF_NAME: ${{env.GITHUB_REF_NAME}}"
          env
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Show Vars
        run: |
          env
