name: Foo Replacer Workflow

on:
  pull_request:

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      PR_BASE_REF: ${{ steps.set-outputs.outputs.PR_BASE_REF }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Display base.ref from Pull Request
        if: github.event_name == 'pull_request'
        id: display-from-pr
        run: |
          echo "PR_BASE_REF=${{ github.event.pull_request.base.ref }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY

      - name: Display PR_BASE_REF
        if: github.event_name == 'pull_request'
        id: set-outputs
        run: |
          echo "PR_BASE_REF=${{ env.PR_BASE_REF }} >> $GITHUB_OUTPUT"
          
  build-selector:
    needs: get-versions
    runs-on: ubuntu-latest
    steps:
      - name: Display tag
        id: full-release-build
        run: |
          echo "needs: ${{ needs.get-versions.outputs.PR_BASE_REF}}"
          echo "env: ${{ env.PR_BASE_REF }}"