name: My Go Builder

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  go-builder:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version-file: go.mod
      #-
      #  name: Run
      #  run: |
      #    go run main.go
      -
        name: Build and run hello.exe
        run: |
          go build -o hello.exe
          ./hello.exe

      - 
        name: Save exe
        uses: actions/upload-artifact@v3
        with:
          name: store-types  
          path: |
              ./hello.exe
