name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version-file: go.mod
      -
        name: Run
        run: |
          go run main.go
      -
        name: Build go
        run: |
          go build -o hello
          hello.exe
