name: My Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  push:
    # branches:
    #  - 'release-[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Display base.ref from Pull Request
        if: ${{ github.event_name == 'pull_request'}}
        id: display-from-pr
        run: |
          echo "Event: ${{ github.event_name }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Event Action: ${{ github.event.action }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_BASE_REF=${{ github.event.pull_request.base.ref }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_STATE=${{ github.event.pull_request.state }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_MERGED=${{ github.event.pull_request.merged }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "GITHUB_SHA=${{ github.sha }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY

      - name: Display base_ref from Push Event
        if: ${{ github.event_name == 'push' }}
        id: display-from-push
        run: |
          echo "Branch Ref: ${{ github.ref }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Event: ${{ github.event_name }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "github.sha: ${{ github.sha }}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Display PR_BASE_REF
        if: ${{ github.event_name == 'pull_request' }}
        id: display-pr-base-ref
        run: |
          echo "PR_BASE_REF=${{ env.PR_BASE_REF }}"
          echo "PR_STATE=${{ env.PR_STATE }}"
          echo "PR_MERGED=${{ env.PR_MERGED }}"
          echo "PR_COMMIT_SHA=${{ env.PR_COMMIT_SHA }}"
          echo "GITHUB_SHA=${{ env.GITHUB_SHA }}"
          
      - name: Just Run Build on Push
        if: ${{ github.event_name == 'push' }}
        id: push-build
        run: |
          echo "Just run a build on sha ${{ github.sha }} with no delivery/release artifacts"
          
      - name: Create Prerelease Candidate Build
        if: ${{ github.event_name == 'pull_request' }} && ${{ env.PR_STATE == 'open' }}
        id: prerelease-build
        run: |
          echo "Just run a prerelease build on sha ${{ github.sha }} with delivery/release artifacts to .rc"
          
      - name: Create Release Build
        if: ${{ github.event_name == 'pull_request' }} && ${{ env.PR_STATE == 'closed' }} && ${{ env.PR_MERGED == 'true' }} && ${{ env.PR_COMMIT_SHA == env.GITHUB_SHA}}
        id: full-release-build
        run: |
          echo "Run a Full Release build on sha ${{ github.sha }} with delivery/release artifacts to final build num"
          
