name: My Release Replacer Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  push:
    # branches:
    #  - 'release-[0-9]*.[0-9]*'

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      PR_BASE_REF: ${{ steps.set-outputs.outputs.PR_BASE_REF }}
      PR_COMMIT_SHA: ${{ steps.set-outputs.outputs.PR_COMMIT_SHA }}
      GITHUB_SHA: ${{ steps.set-outputs.outputs.GITHUB_SHA }}
      PR_BASE_TAG: ${{ steps.set-outputs.outputs.PR_BASE_TAG }}
      FULL_RELEASE:  ${{ steps.set-outputs.outputs.FULL_RELEASE }}
      PRE_RELEASE:  ${{ steps.set-outputs.outputs.PRE_RELEASE }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Display base.ref from Pull Request
        if: github.event_name == 'pull_request'
        id: display-from-pr
        run: |
          echo "Event: ${{ github.event_name }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Event Action: ${{ github.event.action }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_BASE_REF=${{ github.event.pull_request.base.ref }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_STATE=${{ github.event.pull_request.state }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_MERGED=${{ github.event.pull_request.merged }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          echo "GITHUB_SHA=${{ github.sha }}" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY
          baseref="${{ github.event.pull_request.base.ref }}"
          basetag="${baseref#release-}"
          echo "PR_BASE_TAG=$basetag" | tee -a "$GITHUB_ENV" | tee -a $GITHUB_STEP_SUMMARY

      - name: Display base_ref from Push Event
        if: github.event_name == 'push'
        id: display-from-push
        run: |
          echo "Branch Ref: ${{ github.ref }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Event: ${{ github.event_name }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "github.sha: ${{ github.sha }}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Display PR_BASE_REF
        if: github.event_name == 'pull_request'
        id: set-outputs
        run: |
          echo "PR_BASE_REF=${{ env.PR_BASE_REF }} | tee -a $GITHUB_OUTPUT"
          echo "PR_STATE=${{ env.PR_STATE }}"
          echo "PR_MERGED=${{ env.PR_MERGED }}"
          if [[ "${{ env.PR_STATE }}" == "closed" && "${{ env.PR_MERGED }}" == "True" && ("${{ env.PR_COMMIT_SHA }}" == ${{ env.GITHUB_SHA }}") ]]; then
            echo "FULL_RELEASE=True" | tee -a $GITHUB_OUTPUT"
          fi
          if [[ "${{ env.PR_STATE }}" == "open"; then
            echo "PRE_RELEASE=True" | tee -a $GITHUB_OUTPUT"
          fi
          echo "PR_COMMIT_SHA=${{ env.PR_COMMIT_SHA }} | tee -a $GITHUB_OUTPUT"
          echo "GITHUB_SHA=${{ env.GITHUB_SHA }} | tee -a $GITHUB_OUTPUT"
          echo "PR_BASE_TAG=${{ env.PR_BASE_TAG }} | tee -a $GITHUB_OUTPUT"

          
  build-selector:
    needs: get-versions
    runs-on: ubuntu-latest

    steps:
      - name: Just Run Build on Push
        if: github.event_name == 'push'
        id: push-build
        run: |
          echo "Just run a build on sha ${{ github.sha }} with no delivery/release artifacts"

# Before calling this a release or prerelease build DO WE still need to check the state of pulls that match the ${{ env.PR_BASE_REF }}?
# We need to find the latest tag that matches the ${{ env.PR_BASE_REF }}
# To do this, we need to strip the 'release-' from the ref and find the latest repo.tag
# Finding base tag name above as ${{ env.PR_BASE_TAG }}

      - name: Create Prerelease Candidate Build
        if: needs.get-versions.outputs.PRE_RELEASE
        id: prerelease-build
        run: |
          echo "Just run a prerelease build on sha ${{ github.sha }} with delivery/release artifacts to .rc"
          
      - name: Create Release Build
        if: needs.get-versions.outputs.FULL_RELEASE
        id: full-release-build
        run: |
          echo "Run a Full Release build on sha ${{ github.sha }} with delivery/release artifacts to final build num"

  release-type:
    needs: [get-versions, build-selector]
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        id: create_release
#        uses: keyfactor/action-create-release@upd-deprecated
        uses: fiddlermikey/action-create-release@pre
        env:
          MANUAL_VERSION: ${{ env.MANUAL_VERSION }}
        # if: env.IS_PRE_RELEASE == 'True' || env.IS_RELEASE == 'true'
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.SDK_SYNC_PAT }}
          release_name: v${{ needs.get-versions.outputs.PR_BASE_TAG}}
          body: |
            [Changelog](/./CHANGELOG.md) 
            [Readme](/./README.md) 
            For the latest README.md updates visit the [Main Page](/../main) for this repository
          draft: false
          prerelease: ${{ env.IS_PRE_RELEASE == 'True' }}
          prerelease_suffix: rc
          tag_name: ${{ needs.get-versions.outputs.PR_BASE_TAG}}
          auto_increment_type: ${{ (env.IS_PRE_RELEASE == 'True') && 'prerelease' || 'patch' }}
          tag_schema: semantic
          
